USE DATABASE GEOPULSE_DB;
USE SCHEMA RAW;

SELECT
    COUNT(*) AS TOTAL_MOBILITY_PINGS,
    COUNT(DISTINCT ANONYMOUS_USER_ID) AS UNIQUE_USERS,
    COUNT(DISTINCT DATE) AS ACTIVE_DAYS
FROM MOBILITY_PINGS_FEATURED;

SELECT
    MOVEMENT_TYPE,
    COUNT(*) AS MOBILITY_COUNT,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS MOBILITY_PERCENTAGE
FROM MOBILITY_PINGS_FEATURED
GROUP BY MOVEMENT_TYPE
ORDER BY MOBILITY_COUNT DESC;

SELECT
    TIME_PERIOD,
    COUNT(*) AS MOBILITY_COUNT,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS MOBILITY_PERCENTAGE
FROM MOBILITY_PINGS_FEATURED
GROUP BY TIME_PERIOD
ORDER BY MOBILITY_COUNT DESC;

SELECT
    IS_PEAK_HOUR,
    COUNT(*) AS MOBILITY_COUNT
FROM MOBILITY_PINGS_FEATURED
GROUP BY IS_PEAK_HOUR
ORDER BY IS_PEAK_HOUR DESC;

SELECT
    IS_WEEKEND,
    COUNT(*) AS MOBILITY_COUNT
FROM MOBILITY_PINGS_FEATURED
GROUP BY IS_WEEKEND
ORDER BY IS_WEEKEND;

SELECT
    OPPORTUNITY_RANK,
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    TOTAL_MOBILITY_PINGS,
    AVG_DISTANCE_KM,
    CATCHMENT_500M_PCT,
    CATCHMENT_1KM_PCT,
    OPPORTUNITY_SCORE
FROM STORE_OPPORTUNITY_ANALYSIS
ORDER BY OPPORTUNITY_SCORE DESC;

SELECT
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    PINGS_WITHIN_500M,
    PINGS_WITHIN_1KM,
    CATCHMENT_500M_PCT,
    CATCHMENT_1KM_PCT
FROM STORE_OPPORTUNITY_ANALYSIS
ORDER BY CATCHMENT_1KM_PCT DESC;

SELECT
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    TOTAL_MOBILITY_PINGS,
    CAPACITY_PRESSURE_SCORE,
    OPPORTUNITY_SCORE
FROM STORE_OPPORTUNITY_ANALYSIS
ORDER BY CAPACITY_PRESSURE_SCORE DESC;

SELECT
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    NEARBY_STORE_COUNT,
    CANNIBALIZATION_INDICATOR
FROM STORE_OPPORTUNITY_ANALYSIS
ORDER BY NEARBY_STORE_COUNT DESC;

SELECT
    CASE
        WHEN OPPORTUNITY_SCORE <= 40 THEN 'Lower Activity'
        WHEN OPPORTUNITY_SCORE <= 70 THEN 'Moderate Activity'
        ELSE 'Higher Activity'
    END AS PERFORMANCE_CATEGORY,
    COUNT(*) AS STORE_COUNT
FROM STORE_OPPORTUNITY_ANALYSIS
GROUP BY
    CASE
        WHEN OPPORTUNITY_SCORE <= 40 THEN 'Lower Activity'
        WHEN OPPORTUNITY_SCORE <= 70 THEN 'Moderate Activity'
        ELSE 'Higher Activity'
    END
ORDER BY STORE_COUNT DESC;

SELECT
    COUNT(*) AS TOTAL_STORES,
    ROUND(AVG(OPPORTUNITY_SCORE), 2) AS AVG_OPPORTUNITY_SCORE,
    ROUND(MAX(OPPORTUNITY_SCORE), 2) AS MAX_OPPORTUNITY_SCORE,
    ROUND(MIN(OPPORTUNITY_SCORE), 2) AS MIN_OPPORTUNITY_SCORE,
    ROUND(AVG(AVG_DISTANCE_KM), 2) AS AVG_NEAREST_STORE_DISTANCE_KM,
    ROUND(AVG(CATCHMENT_500M_PCT), 2) AS AVG_500M_CATCHMENT_PCT,
    ROUND(AVG(CATCHMENT_1KM_PCT), 2) AS AVG_1KM_CATCHMENT_PCT
FROM STORE_OPPORTUNITY_ANALYSIS;

CREATE OR REPLACE TABLE STORE_BUSINESS_SUMMARY AS
SELECT
    OPPORTUNITY_RANK,
    NEAREST_STORE_ID AS STORE_ID,
    NEAREST_STORE_NAME AS STORE_NAME,
    STORE_TYPE,
    TOTAL_MOBILITY_PINGS,
    AVG_DISTANCE_KM,
    CATCHMENT_500M_PCT,
    CATCHMENT_1KM_PCT,
    MOBILITY_INTENSITY_SCORE,
    CATCHMENT_SCORE,
    CAPACITY_PRESSURE_SCORE,
    NEARBY_STORE_COUNT,
    CANNIBALIZATION_INDICATOR,
    OPPORTUNITY_SCORE,

    CASE
        WHEN OPPORTUNITY_SCORE <= 40 THEN 'Lower Activity'
        WHEN OPPORTUNITY_SCORE <= 70 THEN 'Moderate Activity'
        ELSE 'Higher Activity'
    END AS PERFORMANCE_CATEGORY

FROM STORE_OPPORTUNITY_ANALYSIS;

SELECT *
FROM STORE_BUSINESS_SUMMARY
ORDER BY OPPORTUNITY_SCORE DESC;

SELECT
    PERFORMANCE_CATEGORY,
    COUNT(*) AS STORE_COUNT
FROM STORE_BUSINESS_SUMMARY
GROUP BY PERFORMANCE_CATEGORY
ORDER BY STORE_COUNT DESC;

SELECT
    MIN(OPPORTUNITY_SCORE) AS MIN_SCORE,
    MAX(OPPORTUNITY_SCORE) AS MAX_SCORE,
    ROUND(AVG(OPPORTUNITY_SCORE), 2) AS AVG_SCORE
FROM STORE_BUSINESS_SUMMARY;