USE DATABASE GEOPULSE_DB;
USE SCHEMA RAW;

SELECT *
FROM STORE_BUSINESS_SUMMARY
ORDER BY OPPORTUNITY_SCORE DESC;

SELECT
    COUNT(*) AS TOTAL_STORES,
    ROUND(AVG(OPPORTUNITY_SCORE), 2) AS AVG_OPPORTUNITY_SCORE,
    ROUND(MAX(OPPORTUNITY_SCORE), 2) AS MAX_OPPORTUNITY_SCORE,
    ROUND(MIN(OPPORTUNITY_SCORE), 2) AS MIN_OPPORTUNITY_SCORE,
    ROUND(AVG(AVG_DISTANCE_KM), 2) AS AVG_NEAREST_STORE_DISTANCE_KM,
    ROUND(AVG(CATCHMENT_500M_PCT), 2) AS AVG_500M_CATCHMENT_PCT,
    ROUND(AVG(CATCHMENT_1KM_PCT), 2) AS AVG_1KM_CATCHMENT_PCT
FROM STORE_BUSINESS_SUMMARY;

SELECT
    PERFORMANCE_CATEGORY,
    COUNT(*) AS STORE_COUNT
FROM STORE_BUSINESS_SUMMARY
GROUP BY PERFORMANCE_CATEGORY
ORDER BY STORE_COUNT DESC;

CREATE OR REPLACE VIEW STORE_BUSINESS_ANALYTICS AS
SELECT
    STORE_ID,
    STORE_NAME,
    STORE_TYPE,
    TOTAL_MOBILITY_PINGS,
    AVG_DISTANCE_KM,
    CATCHMENT_500M_PCT,
    CATCHMENT_1KM_PCT,
    MOBILITY_INTENSITY_SCORE,
    CATCHMENT_SCORE,
    CAPACITY_PRESSURE_SCORE,
    NEARBY_STORE_COUNT,
    CANNIBALIZATION_INDICATOR,
    OPPORTUNITY_SCORE,
    PERFORMANCE_CATEGORY
FROM GEOPULSE_DB.RAW.STORE_BUSINESS_SUMMARY;

SELECT *
FROM STORE_BUSINESS_ANALYTICS
ORDER BY OPPORTUNITY_SCORE DESC;

SELECT
    COUNT(*) AS TOTAL_STORES,
    SUM(TOTAL_MOBILITY_PINGS) AS TOTAL_MOBILITY_PINGS,
    ROUND(AVG(OPPORTUNITY_SCORE), 2) AS AVG_OPPORTUNITY_SCORE,
    ROUND(AVG(AVG_DISTANCE_KM), 2) AS AVG_NEAREST_STORE_DISTANCE_KM,
    ROUND(AVG(CATCHMENT_500M_PCT), 2) AS AVG_500M_CATCHMENT_PCT,
    ROUND(AVG(CATCHMENT_1KM_PCT), 2) AS AVG_1KM_CATCHMENT_PCT
FROM STORE_BUSINESS_ANALYTICS;

SELECT
    STORE_ID,
    STORE_NAME,
    STORE_TYPE,
    TOTAL_MOBILITY_PINGS,
    OPPORTUNITY_SCORE,
    PERFORMANCE_CATEGORY
FROM STORE_BUSINESS_ANALYTICS
ORDER BY OPPORTUNITY_SCORE DESC
LIMIT 10;

SELECT
    PERFORMANCE_CATEGORY,
    COUNT(*) AS STORE_COUNT
FROM STORE_BUSINESS_ANALYTICS
GROUP BY PERFORMANCE_CATEGORY
ORDER BY STORE_COUNT DESC;