USE DATABASE GEOPULSE_DB;
USE SCHEMA RAW;


SELECT *
FROM STORE_BUSINESS_ANALYTICS
ORDER BY OPPORTUNITY_SCORE DESC;

CREATE OR REPLACE VIEW GEOPULSE_DASHBOARD_DATA AS
SELECT
    STORE_ID,
    STORE_NAME,
    STORE_TYPE,
    TOTAL_MOBILITY_PINGS,
    AVG_DISTANCE_KM,
    CATCHMENT_500M_PCT,
    CATCHMENT_1KM_PCT,
    MOBILITY_INTENSITY_SCORE,
    CATCHMENT_SCORE,
    CAPACITY_PRESSURE_SCORE,
    NEARBY_STORE_COUNT,
    CANNIBALIZATION_INDICATOR,
    OPPORTUNITY_SCORE,
    PERFORMANCE_CATEGORY
FROM GEOPULSE_DB.RAW.STORE_BUSINESS_SUMMARY;

SELECT *
FROM GEOPULSE_DASHBOARD_DATA;