-- ============================================
-- GeoPulse - Day 8
-- Snowflake Data Warehouse Setup
-- ============================================

-- 1. Create GeoPulse database
CREATE DATABASE IF NOT EXISTS GEOPULSE_DB;

-- 2. Use GeoPulse database
USE DATABASE GEOPULSE_DB;

-- 3. Create raw schema
CREATE SCHEMA IF NOT EXISTS RAW;

-- 4. Create analytics schema
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- 5. Use RAW schema
USE SCHEMA RAW;

-- 6. Check current warehouse
SELECT CURRENT_WAREHOUSE();

-- 7. Check database and schema
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();


USE DATABASE GEOPULSE_DB;
USE SCHEMA RAW;

SHOW TABLES;

SELECT 'MOBILITY_PINGS_FEATURED' AS TABLE_NAME,
       COUNT(*) AS ROW_COUNT
FROM MOBILITY_PINGS_FEATURED

UNION ALL

SELECT 'STORES',
       COUNT(*)
FROM STORES

UNION ALL

SELECT 'ZONES',
       COUNT(*)
FROM ZONES

UNION ALL

SELECT 'MOBILITY_STORE_PROXIMITY',
       COUNT(*)
FROM MOBILITY_STORE_PROXIMITY

UNION ALL

SELECT 'STORE_SPATIAL_ANALYSIS',
       COUNT(*)
FROM STORE_SPATIAL_ANALYSIS

UNION ALL

SELECT 'STORE_OPPORTUNITY_ANALYSIS',
       COUNT(*)
FROM STORE_OPPORTUNITY_ANALYSIS

UNION ALL

SELECT 'STORE_PERFORMANCE_ANALYSIS',
       COUNT(*)
FROM STORE_PERFORMANCE_ANALYSIS;


SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(DISTINCT PING_ID) AS UNIQUE_PINGS
FROM MOBILITY_PINGS_FEATURED;

SELECT
    MOVEMENT_TYPE,
    COUNT(*) AS MOBILITY_COUNT
FROM MOBILITY_PINGS_FEATURED
GROUP BY MOVEMENT_TYPE
ORDER BY MOBILITY_COUNT DESC;

SELECT * 
FROM MOBILITY_PINGS_FEATURED
LIMIT 2;
SELECT * 
FROM STORE_OPPORTUNITY_ANALYSIS
LIMIT 2;
SELECT * 
FROM STORE_PERFORMANCE_ANALYSIS
LIMIT 1;

SELECT
    OPPORTUNITY_RANK,
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    OPPORTUNITY_SCORE,
    CATCHMENT_SCORE,
    CAPACITY_PRESSURE_SCORE
FROM STORE_OPPORTUNITY_ANALYSIS
ORDER BY OPPORTUNITY_SCORE DESC;

DESC TABLE STORE_PERFORMANCE_ANALYSIS;
DESC TABLE MOBILITY_PINGS_FEATURED;

SELECT
    OPPORTUNITY_RANK,
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    OPPORTUNITY_SCORE,
    CATCHMENT_SCORE,
    CAPACITY_PRESSURE_SCORE
FROM STORE_OPPORTUNITY_ANALYSIS
ORDER BY OPPORTUNITY_SCORE DESC;

SELECT TIME_PERIOD
FROM MOBILITY_PINGS_FEATURED

SELECT
    TIME_PERIOD,
    COUNT(*) AS MOBILITY_COUNT
FROM MOBILITY_PINGS_FEATURED
GROUP BY TIME_PERIOD
ORDER BY MOBILITY_COUNT DESC;

USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW STORE_PERFORMANCE_VIEW AS
SELECT
    OPPORTUNITY_RANK,
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    STORE_TYPE,
    OPPORTUNITY_SCORE,
    MOBILITY_INTENSITY_SCORE,
    CATCHMENT_SCORE,
    CAPACITY_PRESSURE_SCORE,
    CANNIBALIZATION_INDICATOR,
    NEARBY_STORE_COUNT
FROM GEOPULSE_DB.RAW.STORE_OPPORTUNITY_ANALYSIS;

SELECT *
FROM STORE_PERFORMANCE_VIEW
ORDER BY OPPORTUNITY_SCORE DESC;

SELECT
    CURRENT_DATABASE() AS DATABASE_NAME,
    CURRENT_SCHEMA() AS SCHEMA_NAME;

    SELECT COUNT(*) AS ANALYTICS_VIEW_ROWS
FROM STORE_PERFORMANCE_VIEW;

